### ISSUE TITLE
implementing timestamps for PMT changes

### ISSUE THREAD

**Issue by sophieclayton** [uwescience/popcycle#28]
@ctberthiaume and I were just talking about adding in some kind of functionality that will read the log files form the instrument and identify when PMTs were changed. then, when you are analysing data after the cruise, you could set filters and gates for each segment of the cruise data and do the analysis all in one go.

**Comment by ctberthiaume** [comment]
Hopefully we don't change the PMT often at all, so it's probably not worth automatically parsing this information.
