### ISSUE TITLE
bug in new function get.opp.by.date

### ISSUE THREAD

**Issue by gmmh** [uwescience/popcycle#30]
get.opp.by.date mostly works except it is failing to return some opp files for date ranges which do exist in my database. Is this because my database is not indexed by time?
Not sure how to provide you with a reproducible example of this without giving you my db

**Comment by fribalet** [comment]
I think I already have your db, give me your time range and I will look at it.
F


—
Francois Ribalet, PhD 
School of Oceanography
University of Washington | Box 357940
Seattle WA 98195
Phone: +1 (206) 221-7841
web: http://armbrustlab.ocean.washington.edu/people/ribalet

**Comment by gmmh** [comment]
I gave Chris the details as he was trouble shooting this yesterday.
In short, I tried to grab hourly intervals and had an error within the
first three days (among other places).
-Gwenn
