### ISSUE TITLE
using multiple files for gating

### ISSUE THREAD

**Issue by sophieclayton** [uwescience/popcycle#31]
is it possible to read in multiple opp files for gating?

e.g. rather than setting the gates on a single opp file using this command:
opp.name <- opp.list[600]

could you set a time range to get all of the data from?

**Comment by fribalet** [comment]
Use the function get.opp.by.date
And then set your gating parameters

**Comment by sophieclayton** [comment]
what format should the date be in?
julian day? or the same format as the evt files?

this would be handy stuff to add to either the wiki or the readme

**Comment by sophieclayton** [comment]
ok, got it...
it should look like this:
end.day <- "2014-07-04 23:00" (%Y-%m-%d %H:%M)

**Comment by sophieclayton** [comment]
ok, so i'm having trouble getting the opp files using a time range...

here's my code:
```
> start.day <- "2014-07-06 23:00"
> end.day <- "2014-07-07 05:00"
> get.opp.by.date(start.day, end.day)
data frame with 0 columns and 0 rows
```
these dates/times are within the range covered by the opp.list, so i'm confused about why this isn't returning a data frame with values in it. 
hopefully a stupid/obvious mistake that i'm missing?

**Comment by fribalet** [comment]
Can you read anything from the database?
Easier if you send me the entire code (along with the location of the database).
F

—
Francois Ribalet, PhD 
School of Oceanography
University of Washington | Box 357940
Seattle WA 98195
Phone: +1 (206) 221-7841
web: http://armbrustlab.ocean.washington.edu/people/ribalet

**Comment by sophieclayton** [comment]
the database is on my local machine.
i am able to read in opp files using get.opp.by.file() with no issues, and
i have checked the opp.list to make sure that the date range that i am
asking for exists in the opp file list...
i'm not sure that there is any other code that would help diagnose the
problem, but here is more or lesss what i did to set it up (after doing the
filtering in a previous session):

>> set.project.location("Documents/MV1405/seaflow")
>> opp.list <- get.opp.files()
>> opp.list[520]
[1] "2014_184/2014-07-03T23-04-49+00-00"

>> start.day <- "2014-07-04 23:00"
>> end.day <- "2014-07-05 23:00"
>> get.opp.by.date(start.day, end.day)
data frame with 0 columns and 0 rows

On Thu, May 7, 2015 at 9:28 AM, Francois Ribalet <notifications@github.com>
wrote:

> Can you read anything from the database?
> Easier if you send me the entire code (along with the location of the
> database).
> F
>
> —
> Francois Ribalet, PhD
> School of Oceanography
> University of Washington | Box 357940
> Seattle WA 98195
> Phone: +1 (206) 221-7841
> web: http://armbrustlab.ocean.washington.edu/people/ribalet
>
> > On May 6, 2015, at 5:47 PM, Sophie Clayton <notifications@github.com>
> wrote:
> >
> > ok, so i'm having trouble getting the opp files using a time range...
> >
> > here's my code:
> >
> > > start.day <- "2014-07-06 23:00"
> > > end.day <- "2014-07-07 05:00"
> > > get.opp.by.date(start.day, end.day)
> > data frame with 0 columns and 0 rows
> > these dates/times are within the range covered by the opp.list, so i'm
> confused about why this isn't returning a data frame with values in it.
> > hopefully a stupid/obvious mistake that i'm missing?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/uwescience/popcycle/issues/31#issuecomment-99661030>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/popcycle/issues/31#issuecomment-99929218>.
>



-- 
Sophie Clayton, PhD
School of Oceanography
Box 357940
University of Washington
Seattle, WA 98195, USA

tel: +1 (206) 685-1047
http://sophieclayton.github.io
http://armbrustlab.ocean.washington.edu/people/clayton

**Comment by fribalet** [comment]
Weird, the julian day should not be included in the name of the opp. That s
why i think it doesn t work. Bug. Do you mind to check the issue with Chris
(I am at home today working on my kitchen...).
Thanks and bonne chance
Francois

**Comment by sophieclayton** [comment]
ah, good to know.
will check with chris today (or more likely monday, now)

enjoy your weekend!
S

On Fri, May 8, 2015 at 3:27 PM, Francois Ribalet <notifications@github.com>
wrote:

> Weird, the julian day should not be included in the name of the opp. That s
> why i think it doesn t work. Bug. Do you mind to check the issue with Chris
> (I am at home today working on my kitchen...).
> Thanks and bonne chance
> Francois
> On May 8, 2015 3:10 PM, "Sophie Clayton" <notifications@github.com> wrote:
>
> > the database is on my local machine.
> > i am able to read in opp files using get.opp.by.file() with no issues,
> and
> > i have checked the opp.list to make sure that the date range that i am
> > asking for exists in the opp file list...
> > i'm not sure that there is any other code that would help diagnose the
> > problem, but here is more or lesss what i did to set it up (after doing
> the
> > filtering in a previous session):
> >
> > >> set.project.location("Documents/MV1405/seaflow")
> > >> opp.list <- get.opp.files()
> > >> opp.list[520]
> > [1] "2014_184/2014-07-03T23-04-49+00-00"
> >
> > >> start.day <- "2014-07-04 23:00"
> > >> end.day <- "2014-07-05 23:00"
> > >> get.opp.by.date(start.day, end.day)
> > data frame with 0 columns and 0 rows
> >
> > On Thu, May 7, 2015 at 9:28 AM, Francois Ribalet <
> notifications@github.com
> > >
> > wrote:
> >
> > > Can you read anything from the database?
> > > Easier if you send me the entire code (along with the location of the
> > > database).
> > > F
> > >
> > > --
> > > Francois Ribalet, PhD
> > > School of Oceanography
> > > University of Washington | Box 357940
> > > Seattle WA 98195
> > > Phone: +1 (206) 221-7841
> > > web: http://armbrustlab.ocean.washington.edu/people/ribalet
> > >
> > > > On May 6, 2015, at 5:47 PM, Sophie Clayton <notifications@github.com
> >
> > > wrote:
> > > >
> > > > ok, so i'm having trouble getting the opp files using a time range...
> > > >
> > > > here's my code:
> > > >
> > > > > start.day <- "2014-07-06 23:00"
> > > > > end.day <- "2014-07-07 05:00"
> > > > > get.opp.by.date(start.day, end.day)
> > > > data frame with 0 columns and 0 rows
> > > > these dates/times are within the range covered by the opp.list, so
> i'm
> > > confused about why this isn't returning a data frame with values in it.
> > > > hopefully a stupid/obvious mistake that i'm missing?
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/uwescience/popcycle/issues/31#issuecomment-99661030
> >.
> > >
> > > >
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/uwescience/popcycle/issues/31#issuecomment-99929218
> > >.
> > >
> >
> >
> >
> > --
> > Sophie Clayton, PhD
> > School of Oceanography
> > Box 357940
> > University of Washington
> > Seattle, WA 98195, USA
> >
> > tel: +1 (206) 685-1047
> > http://sophieclayton.github.io
> > http://armbrustlab.ocean.washington.edu/people/clayton
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/uwescience/popcycle/issues/31#issuecomment-100380327
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/popcycle/issues/31#issuecomment-100385132>.
>



-- 
Sophie Clayton, PhD
School of Oceanography
Box 357940
University of Washington
Seattle, WA 98195, USA

tel: +1 (206) 685-1047
http://sophieclayton.github.io
http://armbrustlab.ocean.washington.edu/people/clayton

**Comment by fribalet** [comment]
I fixed a bug in get.opp.by.date, hopefully this fixes your problem too!
F

—
Francois Ribalet, PhD 
School of Oceanography
University of Washington | Box 357940
Seattle WA 98195
Phone: +1 (206) 221-7841
web: http://armbrustlab.ocean.washington.edu/people/ribalet
